"""Render a CNTC verdict block as a console scorecard and a Markdown file."""
from __future__ import annotations

from pathlib import Path
from typing import Any

_MARK = {"pass": "PASS", "fail": "FAIL", "na": " na "}
_GLYPH = {"pass": "✓", "fail": "✗", "na": "–"}   # ✓ ✗ –
_RESULT_BANNER = {
    "PASS": "PASS  ✓",
    "FAIL": "FAIL  ✗",
    "INCOMPLETE": "INCOMPLETE  –  (some essential tests did not run)",
}


def render_console(v: dict[str, Any]) -> str:
    """A compact, dependency-free scorecard for stdout."""
    lines: list[str] = []
    lines.append("")
    lines.append("  " + "=" * 68)
    lines.append(f"  CNTC VERDICT  —  profile: {v['profile']}  (catalog v{v['catalog_version']})")
    if v.get("title"):
        lines.append(f"  {v['title']}")
    lines.append("  " + "=" * 68)

    rig = v.get("rig") or {}
    if rig:
        rig_str = "  ".join(f"{k}={rig[k]}" for k in ("adapter", "mode", "rig_class")
                            if rig.get(k))
        if rig_str:
            lines.append(f"  rig:  {rig_str}")

    lines.append("")
    for r in v.get("tests", []):
        star = "*" if r["class"] == "essential" else " "
        lines.append(f"   [{_MARK[r['outcome']]}] {star} {r['id']:<6} {r['name'][:44]:<44} {r['detail'][:40]}")

    lines.append("")
    cats = v.get("categories", {})
    for name, c in cats.items():
        score = "n/a" if c["score"] is None else f"{c['score']}%"
        lines.append(f"   {name:<14} passed {c['passed']}  failed {c['failed']}  na {c['na']}   score {score}")

    e = v["essential"]
    lines.append("")
    lines.append(f"   essential gate ({v['gate']['policy']}): "
                 f"{e['passed']} passed / {e['failed']} failed / {e['na']} na  (of {e['total']})")
    if v.get("failed_essentials"):
        lines.append(f"   failed essentials:  {', '.join(v['failed_essentials'])}")
    if v.get("not_run_essentials"):
        lines.append(f"   not-run essentials: {', '.join(v['not_run_essentials'])}")
    for warn in v.get("warnings", []):
        lines.append(f"   ! warning: {warn}")
    lines.append("")
    lines.append(f"  RESULT:  {_RESULT_BANNER.get(v['result'], v['result'])}")
    lines.append("  " + "=" * 68)
    lines.append("")
    return "\n".join(lines)


def render_markdown(v: dict[str, Any]) -> str:
    """A shareable Markdown scorecard (also consumable by the dashboard later)."""
    out: list[str] = []
    out.append(f"# CNTC Scorecard — {v.get('title') or v['profile']}")
    out.append("")
    out.append(f"**Result: {v['result']}**  ")
    out.append(f"Profile: `{v['profile']}` (catalog v{v['catalog_version']})  ")
    if v.get("standards"):
        out.append("Standards: " + ", ".join(f"`{s}`" for s in v["standards"]) + "  ")
    rig = v.get("rig") or {}
    if rig:
        out.append("Rig: " + ", ".join(f"`{k}={val}`" for k, val in rig.items() if val) + "  ")
    out.append("")

    e = v["essential"]
    out.append(f"**Essential gate** (`{v['gate']['policy']}`): "
               f"{e['passed']} passed / {e['failed']} failed / {e['na']} n/a of {e['total']}.")
    if v.get("failed_essentials"):
        out.append(f"Failed essentials: {', '.join('`'+i+'`' for i in v['failed_essentials'])}.")
    if v.get("not_run_essentials"):
        out.append(f"Not-run essentials: {', '.join('`'+i+'`' for i in v['not_run_essentials'])}.")
    for warn in v.get("warnings", []):
        out.append(f"> ⚠️ {warn}")
    out.append("")

    out.append("| Test | Essential | Category | Outcome | Detail |")
    out.append("|------|:---------:|----------|:-------:|--------|")
    for r in v.get("tests", []):
        ess = "yes" if r["class"] == "essential" else ""
        out.append(f"| `{r['id']}` {r['name']} | {ess} | {r['category']} "
                   f"| {_GLYPH[r['outcome']]} {r['outcome']} | {r['detail']} |")
    out.append("")

    out.append("| Category | Passed | Failed | n/a | Score |")
    out.append("|----------|:------:|:------:|:---:|:-----:|")
    for name, c in v.get("categories", {}).items():
        score = "n/a" if c["score"] is None else f"{c['score']}%"
        out.append(f"| {name} | {c['passed']} | {c['failed']} | {c['na']} | {score} |")
    out.append("")
    out.append("> Generated by the CNTC verdict layer. `PASS` = every essential test passed; "
               "`INCOMPLETE` = some essential test did not run (never a silent pass); "
               "`FAIL` = an essential test failed.")
    out.append("")
    return "\n".join(out)


_RESULT_COLOR = {"PASS": "#1a7f37", "FAIL": "#cf222e", "INCOMPLETE": "#9a6700"}
_OUTCOME_COLOR = {"pass": "#1a7f37", "fail": "#cf222e", "na": "#8b949e"}


def _esc(s: Any) -> str:
    return (str(s).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))


def render_html(v: dict[str, Any]) -> str:
    """A self-contained, dependency-free HTML scorecard (inline CSS, no JS). Openable in any
    browser and embeddable by the dashboard (it can iframe/serve this file)."""
    res = v["result"]
    color = _RESULT_COLOR.get(res, "#57606a")
    rows = []
    for r in v.get("tests", []):
        oc = _OUTCOME_COLOR[r["outcome"]]
        star = " ★" if r["class"] == "essential" else ""
        rows.append(
            f'<tr><td><code>{_esc(r["id"])}</code>{star}</td><td>{_esc(r["name"])}</td>'
            f'<td>{_esc(r["category"])}</td>'
            f'<td style="color:{oc};font-weight:600">{r["outcome"].upper()}</td>'
            f'<td style="color:#57606a">{_esc(r["detail"])}</td></tr>')
    cat_rows = []
    for name, c in v.get("categories", {}).items():
        score = "n/a" if c["score"] is None else f'{c["score"]}%'
        cat_rows.append(f'<tr><td>{_esc(name)}</td><td>{c["passed"]}</td>'
                        f'<td>{c["failed"]}</td><td>{c["na"]}</td><td>{score}</td></tr>')
    e = v["essential"]
    rig = "  ·  ".join(f"{k}={_esc(val)}" for k, val in (v.get("rig") or {}).items() if val)
    warns = "".join(f'<p style="color:#9a6700">⚠️ {_esc(w)}</p>' for w in v.get("warnings", []))
    standards = ", ".join(_esc(s) for s in v.get("standards", []))
    return f"""<!doctype html><html><head><meta charset="utf-8">
<title>CNTC Scorecard — {_esc(v.get('title') or v['profile'])}</title>
<style>
 body{{font:14px/1.5 -apple-system,Segoe UI,Roboto,sans-serif;color:#1f2328;max-width:900px;margin:2rem auto;padding:0 1rem}}
 .banner{{display:inline-block;padding:.35rem .9rem;border-radius:6px;color:#fff;font-weight:700;background:{color}}}
 table{{border-collapse:collapse;width:100%;margin:1rem 0;font-size:13px}}
 th,td{{border:1px solid #d0d7de;padding:.35rem .5rem;text-align:left}}
 th{{background:#f6f8fa}} code{{background:#eff1f3;padding:0 .3rem;border-radius:4px}}
 .meta{{color:#57606a;font-size:13px}}
</style></head><body>
<h1>CNTC Scorecard <span class="banner">{res}</span></h1>
<p class="meta">Profile <b>{_esc(v['profile'])}</b> (catalog v{_esc(v['catalog_version'])})
 &nbsp;·&nbsp; {_esc(v.get('title',''))}</p>
<p class="meta">Standards: {standards}</p>
<p class="meta">Rig: {rig or '—'}</p>
<p><b>Essential gate</b> (<code>{_esc(v['gate']['policy'])}</code>):
 {e['passed']} passed / {e['failed']} failed / {e['na']} n/a of {e['total']}.</p>
{warns}
<table><thead><tr><th>Test</th><th>Name</th><th>Category</th><th>Outcome</th><th>Detail</th></tr></thead>
<tbody>{''.join(rows)}</tbody></table>
<h3>Categories</h3>
<table><thead><tr><th>Category</th><th>Passed</th><th>Failed</th><th>n/a</th><th>Score</th></tr></thead>
<tbody>{''.join(cat_rows)}</tbody></table>
<p class="meta">★ = essential. PASS = every essential passed; INCOMPLETE = an essential did not
 run (never a silent pass); FAIL = an essential failed. Generated by the CNTC verdict layer.</p>
</body></html>"""


def write_scorecard(campaign_dir: str | Path, verdict: dict[str, Any]) -> Path:
    """Write scorecard.md + scorecard.html into the campaign directory; return the .md path."""
    d = Path(campaign_dir)
    d.mkdir(parents=True, exist_ok=True)
    md = d / "scorecard.md"
    md.write_text(render_markdown(verdict))
    (d / "scorecard.html").write_text(render_html(verdict))
    return md
